SplitSet3R/Split

- database/migrations/2017_03_14_030738_CreateGroupMemberTable.php
- database/migrations/2017_03_24_014813_CreateGroupExpensesTable.php
- database/migrations/2017_03_24_020639_UpdateGroupExpensesTable.php
- database/migrations/2017_03_24_021429_CreateGroupSharedExpensesTable.php
- database/migrations/2017_03_24_044928_UpdateGroupSharedExpensesTable.php
- database/migrations/2017_03_24_045227_CreateGroupSettledExpensesTable.php
- database/migrations/2017_03_24_045544_UpdateGroupSettledExpensesTable.php
> added group expenses schema to the database

- app/Http/Controllers/DashboardController.php
- app/User.php
- public/js/custom.js
- resources/views/dashboard.blade.php
- resources/views/layouts/app.blade.php
- resources/views/search-friends.blade.php
- routes/web.php
> Front end add friend

- app/Http/Middleware/RedirectIfAuthenticated.php
- public/css/sidebar.css
- resources/views/dashboard.blade.php
- resources/views/includes/sidebar.blade.php
- resources/views/layouts/app.blade.php
- resources/views/search-friends.blade.php
- resources/views/welcome.blade.php
- routes/web.php
-FriendsController added, niko's search friends page linked upto dashboard. Click add friends from the dashboard to access niko's page
-Sidebar in app.blade layout. Sidebard will appear on every page if use is logged in. Sidebar only shows if user logged in. sidebar and main panel wrapped in wrapper in app.blade. any main content must have "main-panel" styling.
-Updated route middleware so that the user will be redirected to the dashboard if they try to access the welcome page when logged in. The sidebar styling doesn't work very well with the landing page anyhow
Quickly merge please
> Bryn dashboard

- app/Http/Controllers/AjaxController.php
- app/Http/Controllers/SearchController.php
- routes/web.php
Implemented what was needed in bryn's branch to make the backend working.
Note: I'm not sure what the correct way to process the fact that username1 and username2 can be used interchangeably. This shouldn't be a problem as long as we run the same checks before adding friends, we should also be checking to make sure that a user can't add his or herself as a friend.
@SplitSet3R/box-end make sure to check Friend status before adding or ->save() will fail.
Note: @SplitSet3R/front-end, currently if someone is already added as a friend, should we exclude that user from the search? If so, we'll have to make another branch for that.
> Feature search backend

- public/css/sidebar.css
- resources/views/dashboard.blade.php
- resources/views/includes/sidebar.blade.php
Changed adding an expense from collapsible to modal.
Also changed the input type for amounts to better suit currency input.
This branch is behind by some commits, but shouldn't be too hard to merge as I just changed the dashboard blade, sidebar blade, and some css.
> Modal add expense

- app/Http/Controllers/AjaxController.php
- resources/views/friends.blade.php
> fix accept friend-request-issue

- app/Http/Controllers/Auth/RegisterController.php
> Fixed username conflicts for registration

- app/Http/Controllers/ProfileController.php
- app/User.php
- database/migrations/2017_03_13_211341_CreateUsersTable.php
- routes/web.php
Code quite verbose, need to slim down after we finalize how front end would like to display editing functionality.
Updated migrations/models to account for Bio and Avatar as well.
> Feature edit profile

- composer.json
- composer.lock
- config/app.php
Just want to be able to use laravel forms - installing the laravel collective package does this.
Not sure if I should've committed the composer files - if not, then I can revert my commit to just the app.php changes.
Need to run **_composer update_** and **_composer require laravelcollective/html_**.
> Want to use laravel forms

- app/CustomClasses/Groups/GroupsStatusCodeEnum.php
- app/Group.php
- app/GroupMember.php
- app/Http/Controllers/GroupCreateController.php
- app/Http/Controllers/ProfileController.php
- app/User.php
- composer.json
- composer.lock
- config/app.php
- database/migrations/2017_03_13_211341_CreateUsersTable.php
- routes/web.php
I added comment questions in the code. And this needs an issue
> Group create controller

- app/Http/Controllers/SettleExpenseController.php
- app/SettledExpense.php
- app/SharedExpense.php
- database/migrations/2017_03_14_024733_UpdateSharedExpensesTable.php
- database/migrations/2017_03_14_030350_UpdateSettledExpensesTable.php
- routes/web.php
Only include settling of SharedExpenses
contains schema updates.
> Feature settle expenserino

- app/Http/Controllers/ProfileController.php
- public/css/legacy/images.css
- public/css/sidebar.css
- resources/views/profile.blade.php
Edit profile functionality hooked up with back-end and working. Tested against database and saves alright.
> Edit Profile works now

- app/Http/Controllers/GroupDashboardController.php
will probably need to change return
> Group dashboard controller

- app/Http/Controllers/FriendController.php
- app/Http/Controllers/GroupController.php
- app/Http/Controllers/GroupCreateController.php
- app/Http/Controllers/GroupDashboardController.php
- app/Http/Controllers/SettleExpenseController.php
> we forgot construct

- public/css/profile.css
- resources/views/layouts/app.blade.php
> Fix profile image css

- resources/views/includes/sidebar.blade.php
- resources/views/layouts/app.blade.php
As the title says.
_Note:_ when I was testing - after clicking user profile, the color updated, but the text color and icon was gray. Not sure if just occurring on my machine or not - however, hardcoded text to be white just in case.
For testing, you can remove those two jquery css lines under the profile case and check to see if you get gray/darkish text - if not, then problem's my machine and we can remove the unnecessary jquery calls.
> Sidebar color now updates based on current page

- app/Expense.php
- app/Http/Controllers/DashboardController.php
- app/Http/Controllers/ExpenseController.php
- app/SharedExpense.php
- public/css/common/split.css
- resources/views/dashboard.blade.php
- resources/views/includes/sidebar.blade.php
- resources/views/layouts/app.blade.php
- routes/web.php
Refactored back end for adding expense
> Refactored the back end of adding expense

- app/Http/Controllers/AjaxController.php
- app/Http/Controllers/ProfileController.php
- config/constants.php
- resources/views/debug.blade.php
- resources/views/friends.blade.php
- resources/views/profile.blade.php
- resources/views/search-friends.blade.php
Links to friends' profile page added. Profile page responds to permissions which have also been added. Query to determine permissions also fixed. Unnecessary sidebar include removed from profile blade. Add friend button added to profile is user is not their friend. Personal information about user hidden if not friend. Edit profile button only shows when looking at own profile.
> Friend profile functionality added for all permissions. Friend links accessable where available.

- app/Http/Controllers/DashboardController.php
Not to sure what ttl and bal means
atm its like this:
ttl = sum of amount column in expense where its owned by user
bal = total owed - total owing
> added summary to dashboardController

- app/Http/Controllers/DashboardController.php
- app/Http/Controllers/SettleExpenseController.php
- database/migrations/2017_03_13_211120_CreateExpensesTable.php
- resources/views/dashboard.blade.php
- resources/views/includes/sidebar.blade.php
- resources/views/profile.blade.php
- Removed unused table list from sidebar
- Deleting shared expense cascade deletes expense
- Summary displays now, hooray
- Modified settled expenses table columns to display settled expenses data from db
***right now this displays ALL settled expenses for ALL users -> for future, let's work towards displaying expenses settled expenses that include ONLY the logged in user, check out image***
> Fe stuff before re-deploy and demo

- app/Http/Controllers/ExpenseController.php
added expense notfication manager call
> fix expense notifciation
